# Generated by Django 4.2.28 on 2026-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="provider_instance",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "Github"),
                    ("gitlab", "GitLab"),
                    ("gitea", "Gitea"),
                    ("oidc", "OpenID Connect"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("provider", "provider_instance", "provider_account_id")},
        ),
    ]
